In [1]:
import pandas as pd

In [2]:
pdf=pd.read_csv("heart_failure_clinical_records_dataset.csv")

In [3]:
pdf

,age,anaemia,creatinine_phosphokinase,diabetes,ejection_fraction,high_blood_pressure,platelets,serum_creatinine,serum_sodium,sex,smoking,time,DEATH_EVENT
0,75.0,0,582,0,20,1,265000.00,1.9,130,1,0,4,1
1,55.0,0,7861,0,38,0,263358.03,1.1,136,1,0,6,1
2,65.0,0,146,0,20,0,162000.00,1.3,129,1,1,7,1
3,50.0,1,111,0,20,0,210000.00,1.9,137,1,0,7,1
4,65.0,1,160,1,20,0,327000.00,2.7,116,0,0,8,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...
294,62.0,0,61,1,38,1,155000.00,1.1,143,1,1,270,0
295,55.0,0,1820,0,38,0,270000.00,1.2,139,0,0,271,0
296,45.0,0,2060,1,60,0,742000.00,0.8,138,0,0,278,0
297,45.0,0,2413,0,38,0,140000.00,1.4,140,1,1,280,0
298,50.0,0,196,0,45,0,395000.00,1.6,136,1,1,285,0

In [4]:
pdf.info()

<class 'pandas.DataFrame'>
RangeIndex: 299 entries, 0 to 298
Data columns (total 13 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   age                       299 non-null    float64
 1   anaemia                   299 non-null    int64
 2   creatinine_phosphokinase  299 non-null    int64
 3   diabetes                  299 non-null    int64
 4   ejection_fraction         299 non-null    int64
 5   high_blood_pressure       299 non-null    int64
 6   platelets                 299 non-null    float64
 7   serum_creatinine          299 non-null    float64
 8   serum_sodium              299 non-null    int64
 9   sex                       299 non-null    int64
 10  smoking                   299 non-null    int64
 11  time                      299 non-null    int64
 12  DEATH_EVENT               299 non-null    int64
dtypes: float64(3), int64(10)
memory usage: 30.5 KB

In [5]:
pdf.isna().sum()

age                         0
anaemia                     0
creatinine_phosphokinase    0
diabetes                    0
ejection_fraction           0
high_blood_pressure         0
platelets                   0
serum_creatinine            0
serum_sodium                0
sex                         0
smoking                     0
time                        0
DEATH_EVENT                 0
dtype: int64

In [6]:
pdf.duplicated().sum()

np.int64(0)

In [7]:
pdf.corr()

,age,anaemia,creatinine_phosphokinase,diabetes,ejection_fraction,high_blood_pressure,platelets,serum_creatinine,serum_sodium,sex,smoking,time,DEATH_EVENT
age,1.000000,0.088006,-0.081584,-0.101012,0.060098,0.093289,-0.052354,0.159187,-0.045966,0.065430,0.018668,-0.224068,0.253729
anaemia,0.088006,1.000000,-0.190741,-0.012729,0.031557,0.038182,-0.043786,0.052174,0.041882,-0.094769,-0.107290,-0.141414,0.066270
creatinine_phosphokinase,-0.081584,-0.190741,1.000000,-0.009639,-0.044080,-0.070590,0.024463,-0.016408,0.059550,0.079791,0.002421,-0.009346,0.062728
diabetes,-0.101012,-0.012729,-0.009639,1.000000,-0.004850,-0.012732,0.092193,-0.046975,-0.089551,-0.157730,-0.147173,0.033726,-0.001943
ejection_fraction,0.060098,0.031557,-0.044080,-0.004850,1.000000,0.024445,0.072177,-0.011302,0.175902,-0.148386,-0.067315,0.041729,-0.268603
high_blood_pressure,0.093289,0.038182,-0.070590,-0.012732,0.024445,1.000000,0.049963,-0.004935,0.037109,-0.104615,-0.055711,-0.196439,0.079351
platelets,-0.052354,-0.043786,0.024463,0.092193,0.072177,0.049963,1.000000,-0.041198,0.062125,-0.125120,0.028234,0.010514,-0.049139
serum_creatinine,0.159187,0.052174,-0.016408,-0.046975,-0.011302,-0.004935,-0.041198,1.000000,-0.189095,0.006970,-0.027414,-0.149315,0.294278
serum_sodium,-0.045966,0.041882,0.059550,-0.089551,0.175902,0.037109,0.062125,-0.189095,1.000000,-0.027566,0.004813,0.087640,-0.195204
sex,0.065430,-0.094769,0.079791,-0.157730,-0.148386,-0.104615,-0.125120,0.006970,-0.027566,1.000000,0.445892,-0.015608,-0.004316
smoking,0.018668,-0.107290,0.002421,-0.147173,-0.067315,-0.055711,0.028234,-0.027414,0.004813,0.445892,1.000000,-0.022839,-0.012623
time,-0.224068,-0.141414,-0.009346,0.033726,0.041729,-0.196439,0.010514,-0.149315,0.087640,-0.015608,-0.022839,1.000000,-0.526964
DEATH_EVENT,0.253729,0.066270,0.062728,-0.001943,-0.268603,0.079351,-0.049139,0.294278,-0.195204,-0.004316,-0.012623,-0.526964,1.000000

In [8]:
X=pdf.drop(["DEATH_EVENT"],axis=1)
y=pdf.DEATH_EVENT

In [9]:
X

,age,anaemia,creatinine_phosphokinase,diabetes,ejection_fraction,high_blood_pressure,platelets,serum_creatinine,serum_sodium,sex,smoking,time
0,75.0,0,582,0,20,1,265000.00,1.9,130,1,0,4
1,55.0,0,7861,0,38,0,263358.03,1.1,136,1,0,6
2,65.0,0,146,0,20,0,162000.00,1.3,129,1,1,7
3,50.0,1,111,0,20,0,210000.00,1.9,137,1,0,7
4,65.0,1,160,1,20,0,327000.00,2.7,116,0,0,8
...,...,...,...,...,...,...,...,...,...,...,...,...
294,62.0,0,61,1,38,1,155000.00,1.1,143,1,1,270
295,55.0,0,1820,0,38,0,270000.00,1.2,139,0,0,271
296,45.0,0,2060,1,60,0,742000.00,0.8,138,0,0,278
297,45.0,0,2413,0,38,0,140000.00,1.4,140,1,1,280
298,50.0,0,196,0,45,0,395000.00,1.6,136,1,1,285

In [10]:
y

0      1
1      1
2      1
3      1
4      1
      ..
294    0
295    0
296    0
297    0
298    0
Name: DEATH_EVENT, Length: 299, dtype: int64

In [11]:
from sklearn.model_selection import train_test_split

In [12]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.25,random_state=42)

In [13]:
X_train.shape,X_test.shape,y_train.shape,y_test.shape

((224, 12), (75, 12), (224,), (75,))

In [14]:
import warnings
warnings.filterwarnings("ignore")

In [15]:
from sklearn.linear_model import LogisticRegression

In [16]:
lr=LogisticRegression()

In [17]:
lr.fit(X_train,y_train)

LogisticRegression()

In [18]:
y_train_pred = lr.predict(X_train)

In [19]:
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score

In [20]:
confusion_matrix(y_train, y_train_pred)

array([[144,  15],
       [ 23,  42]])

In [21]:
accuracy_score(y_train, y_train_pred)

0.8303571428571429

In [22]:
print(classification_report(y_train, y_train_pred))

              precision    recall  f1-score   support

           0       0.86      0.91      0.88       159
           1       0.74      0.65      0.69        65

    accuracy                           0.83       224
   macro avg       0.80      0.78      0.79       224
weighted avg       0.83      0.83      0.83       224

In [23]:
pdf.DEATH_EVENT.value_counts()

DEATH_EVENT
0    203
1     96
Name: count, dtype: int64

In [24]:
from imblearn.over_sampling import SMOTE

In [25]:
smote=SMOTE(sampling_strategy="minority",random_state=42)

In [26]:
X_train_sm,y_train_sm=smote.fit_resample(X_train,y_train)

In [27]:
y_train_sm.value_counts()

DEATH_EVENT
0    159
1    159
Name: count, dtype: int64

In [28]:
lr=LogisticRegression()

In [29]:
lr.fit(X_train_sm,y_train_sm)

LogisticRegression()

In [30]:
print(classification_report(y_train_sm,lr.predict(X_train_sm)))

              precision    recall  f1-score   support

           0       0.85      0.81      0.83       159
           1       0.82      0.86      0.84       159

    accuracy                           0.83       318
   macro avg       0.83      0.83      0.83       318
weighted avg       0.83      0.83      0.83       318

In [31]:
from sklearn.preprocessing import MinMaxScaler, StandardScaler

In [32]:
min_max_scaler=MinMaxScaler()

In [33]:
scale_X_train=min_max_scaler.fit_transform(X_train_sm)
scale_X_test=min_max_scaler.transform(X_test)

In [34]:
lr=LogisticRegression()

In [36]:
lr.fit(X_train_sm,y_train_sm)

LogisticRegression()

In [37]:
y_scale_train=lr.predict(scale_X_train)

In [38]:
print(classification_report(y_train_sm, y_scale_train))

              precision    recall  f1-score   support

           0       0.77      0.75      0.76       159
           1       0.75      0.77      0.76       159

    accuracy                           0.76       318
   macro avg       0.76      0.76      0.76       318
weighted avg       0.76      0.76      0.76       318

In [39]:
from sklearn.svm import SVC

In [40]:
sv = SVC(kernel= "poly")

In [41]:
sv.fit(scale_X_train,y_train_sm)

SVC(kernel='poly')

In [42]:
sv_X_train=sv.predict(scale_X_train)

In [43]:
print(classification_report(y_train_sm, sv_X_train))

              precision    recall  f1-score   support

           0       0.96      0.89      0.92       159
           1       0.89      0.96      0.93       159

    accuracy                           0.92       318
   macro avg       0.93      0.92      0.92       318
weighted avg       0.93      0.92      0.92       318